### ISSUE TITLE
nvmw install current version when without version?

### ISSUE THREAD

**Issue by edwardchanjw** [hakobera/nvmw#31]
As title, can nvmw install current version when without version argument passing to nvmw install.

Thanks!

**Comment by amullins83** [comment]
I know it's been half a year since you submitted this, but what exactly are you trying to do? Do you want to reinstall the currently active version or get the latest released version (like `nvm install stable` on other systems)?

**Comment by edwardchanjw** [comment]
Actually trying to get the latest released version without the need of specify the version.

**Comment by amullins83** [comment]
I'm working on it. There's a helpful "latest" folder in `nodejs.org/dist`, but there's (naturally) no `latest` tag in GitHub, so we'll need to figure out a different way to parse version numbers to get NPM. We'll eventually need to rewrite `get_npm.js` anyway, since NPM 2.0 can't be obtained from from nodejs.org. I think this is a consequence of NPM being its own company now.

**Comment by edwardchanjw** [comment]
Thank for the help!

**Comment by hakobera** [comment]
@edwardchanjw @amullins83 Now nvm support `latest` version (but latest means latest stable version, it different from nvm). and also support io.js. Try `nvmw install latest`

For more detail see #36.
