### ISSUE TITLE
In 64bit os ,can not install 32bit node

### ISSUE THREAD

**Issue by hashplus** [hakobera/nvmw#33]
In 64bit os ,can not install 32bit node.

**Comment by amullins83** [comment]
To determine architecture, nvmw looks for an environment variable `"%PROGRAMFILES(X86)%"`. If a file or directory exists at that path, 64-bit is assumed, otherwise 32-bit is assumed. So, a work-around is to:

1. Save the current value to a temp variable: `set "PF32=%PROGRAMFILES(X86)%"`
2. Unset the variable: `set "PROGRAMFILES(X86)"`
3. Run `nvmw install` with whatever version
4. Restore the system variable: `set "PROGRAMFILES(X86)=%PF32%"`

I tested this on Windows 7 x64 with a fresh pull from master this morning.

**Comment by hakobera** [comment]
Solved by https://github.com/hakobera/nvmw/pull/34
